// ROAD NETWORK — generated by tools/road-network-editor.html
// nodes = junctions (locations come from data.js automatically).
// edges = two-way road segments; `via` adds bend points. [x, y] in map %.

window.ROAD_NETWORK = {
  nodes: {
    "j1": [30.9, 70.1],
    "j2": [30.5, 71],
    "j3": [31, 71],
    "j4": [30.1, 71],
    "j5": [29.9, 71.4],
    "j6": [28.9, 71.4],
    "j7": [30.4, 68.6],
    "j8": [31.3, 67.9],
    "j9": [31.1, 67.6],
    "j10": [31.2, 67.3],
    "j11": [31.2, 66.8],
    "j12": [31.1, 66.6],
    "j13": [29.8, 68.1],
    "j14": [28.7, 67.4],
    "j15": [27.8, 66.9],
    "j16": [27.6, 66.4],
    "j17": [27.2, 66.4],
    "j18": [26.7, 66.2],
    "j19": [26.6, 66.1],
    "j20": [28.9, 66.5]
  },

  edges: [
    { a: "rolent_city", b: "bright_house" },
    { a: "j1", b: "bright_house" },
    { a: "rolent_city", b: "j8" },
    { a: "j8", b: "j9" },
    { a: "j9", b: "esmelas" },
    { a: "j9", b: "j10" },
    { a: "j10", b: "j11" },
    { a: "j11", b: "j12" },
    { a: "j12", b: "malga" },
    { a: "j1", b: "j2" },
    { a: "j3", b: "j2" },
    { a: "j3", b: "mistwald" },
    { a: "j2", b: "j4" },
    { a: "j4", b: "j5" },
    { a: "j5", b: "j6" },
    { a: "rolent_city", b: "j7" },
    { a: "j7", b: "perzel" },
    { a: "j7", b: "j13" },
    { a: "j13", b: "j14" },
    { a: "j20", b: "j14" },
    { a: "j14", b: "j15" },
    { a: "j15", b: "j16" },
    { a: "j16", b: "j17" },
    { a: "j17", b: "j18" },
    { a: "j18", b: "j19" },
    { a: "j19", b: "bose_city" }
  ]
};

// Optional hard overrides, keyed "from>to". Checked before the network search.
window.ROUTES = {
};
